### ISSUE TITLE
1.4-pixel-perfect

### ISSUE THREAD

**Issue by austineady** [austineady/1.4-pixel-perfect#1]
### Tasks
- **Getting Started**
  - [x] Follow the assignment instructions to create a new issue.
  - [x] Follow the assignment instructions to create a new repository.
  - [x] Create and commit `index.html`
  - [x] Follow the assignment instructions to create a new pull request.
  - [x] **Read [this article](http://diveintohtml5.info/semantics.html) about
    semantic HTML.**
- **Slice the Comp**
  Annotate the following images to denote:
  - the tag names and bounding boxes of semantic block-level elements
  - essential CSS properties and values like `margin` and `padding`
  - anything else that will help you execute the design!
  - [x] Checkpoint: Sliced the page header, annotated and committed!
  - [x] Checkpoint: Sliced the page footer, annotated and committed!
  - [x] Checkpoint: Sliced the main article, annotated and committed!
  - [x] Checkpoint: Sliced the article header, annotated and committed!
  - [x] Checkpoint: Sliced the article footer, annotated and committed!
  - [ ] Checkpoint: Sliced the sidebar, annotated and committed!
  - [ ] Mission Complete!
- **Code the Comp!**
  - [x] Checkpoint: Basic HTML structure committed!
  - [x] Checkpoint: Basic layout CSS committed!
  - [x] Checkpoint: Pixel perfect page header committed!
  - [x] Checkpoint: Pixel perfect page footer committed!
  - [x] Checkpoint: Pixel perfect column layout committed!
  - [x] Checkpoint: Pixel perfect layout and typography committed!
  - [ ] Checkpoint: Links with hover states committed!
  - [ ] Mission complete!
